### PR TITLE
Ll file restructure

### PR DESCRIPTION
**Pull request by Yikachu**
uwu

### CODE REVIEW

**Review by leo-cf-tian — CHANGES_REQUESTED** [review]
Please rename files that do not follow the `PascalCase` naming convention.

Examples of violations include 
- Dungeon_Tileset.png
- Health Bar.png
- pixil-frame-0 (2).png
Among others

Also the ErrorTile file is spelt wrong

**Comment by arthu-rguo** [comment]
delete SampleScene

**Review by leo-cf-tian — APPROVED** [review]
Looks good but, please name PixilFrame0 to something more descriptive. Feel free to merge after renaming.

**Comment by Yikachu** [comment]
I have no idea what PixilFrame0 does or is supposed to be. It was not my file.

**Pull request merged**
